language: objective-c

notifications:
  email:
    on_success: never
    on_failure: change
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/cc2592f750965c320c96
    on_success: change
    on_failure: always
    on_start: false

script: 'curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh'

git:
  depth: 10

branches:
  only:
    - master
